// 40_compilations（公開安全な匿名化ナレッジ）から、Edge Functionが実行時に使う
// セクション索引を生成する。Geminiが file_citation を返さないときでも、質問＋パートの
// キーワードで決定的に該当セクションを選び、本物の抜粋付き出典を出すために使う。
//
// 生成物 supabase/functions/_shared/knowledge-index.ts は自動生成。手で編集しない。
// 30_sources（非公開アーカイブ）は対象に含めない（公開リポジトリへ本文を出さないため）。
//
// 再生成: npm run knowledge:build-index
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { parse } from "yaml";
import { listFiles, readUtf8 } from "./file-utils.ts";

interface KnowledgeSection {
  source_id: string;
  title: string;
  part: string;
  heading: string;
  text: string;
}

async function main(): Promise<void> {
  const root = path.resolve("knowledge", "40_compilations");
  const files = (await listFiles(root, (filePath) => filePath.endsWith(".md"))).sort();
  const sections: KnowledgeSection[] = [];
  for (const filePath of files) {
    const content = await readUtf8(filePath);
    const { frontMatter, body } = splitFrontMatter(content);
    const sourceId = typeof frontMatter.source_id === "string" ? frontMatter.source_id : path.basename(filePath);
    const title = typeof frontMatter.title === "string" ? frontMatter.title : path.basename(filePath, ".md");
    const part = typeof frontMatter.part === "string" ? frontMatter.part : "all";
    for (const section of splitSections(body)) {
      sections.push({ source_id: sourceId, title, part, heading: section.heading, text: section.text });
    }
  }

  const header = "// AUTO-GENERATED by scripts/build-knowledge-index.ts. Do not edit by hand.\n"
    + "// 再生成: npm run knowledge:build-index\n\n"
    + "export interface KnowledgeSection {\n"
    + "  source_id: string;\n  title: string;\n  part: string;\n  heading: string;\n  text: string;\n}\n\n"
    + "export const KNOWLEDGE_INDEX: readonly KnowledgeSection[] = ";
  const outPath = path.resolve("supabase", "functions", "_shared", "knowledge-index.ts");
  await writeFile(outPath, `${header}${JSON.stringify(sections, null, 0)};\n`, "utf8");
  console.log(`knowledge index built: ${files.length} files, ${sections.length} sections -> ${path.relative(process.cwd(), outPath)}`);
}

function splitFrontMatter(content: string): { frontMatter: Record<string, unknown>; body: string } {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/u);
  if (!match?.[1]) return { frontMatter: {}, body: content };
  const value: unknown = parse(match[1]);
  return {
    frontMatter: value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {},
    body: match[2] ?? "",
  };
}

// 本文を ## / ### 見出しごとのセクションへ分割する。最初の見出し前の導入部は「（概要）」にまとめる。
function splitSections(body: string): { heading: string; text: string }[] {
  const lines = body.split(/\r?\n/u);
  const sections: { heading: string; lines: string[] }[] = [];
  let current: { heading: string; lines: string[] } = { heading: "（概要）", lines: [] };
  for (const line of lines) {
    const headingMatch = line.match(/^#{2,3}\s+(.+?)\s*$/u);
    if (headingMatch?.[1]) {
      if (current.lines.some((l) => l.trim().length > 0)) sections.push(current);
      current = { heading: headingMatch[1].trim(), lines: [line] };
    } else {
      current.lines.push(line);
    }
  }
  if (current.lines.some((l) => l.trim().length > 0)) sections.push(current);
  return sections
    .map((section) => ({ heading: section.heading, text: section.lines.join("\n").trim() }))
    .filter((section) => section.text.length > 0);
}

void main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
